### ISSUE TITLE
Confirm agreement with Kevin of observed data events in bin C after all selection cuts

### ISSUE THREAD

**Issue by sixie** [cms-lpc-llp/DelayedPhotonLimit#1]

**Comment by thongonary** [comment]
Difference in all bins (computed as (Thong - Kevin)/Kevin %:
![BinDiffDistribution](https://user-images.githubusercontent.com/10479549/75410197-e44dcd00-58cf-11ea-88a6-dc304bb61232.png)

Difference by each bin:
![DiffByBin](https://user-images.githubusercontent.com/10479549/75410210-ed3e9e80-58cf-11ea-9019-da64309244b0.png)

So in signal bin (bin C), the differences are within 20%. 

Detailed numbers can be found in here:
[DataYieldComparison.txt](https://github.com/cms-lpc-llp/DelayedPhotonLimit/files/4259377/DataYieldComparison.txt)

**Comment by thongonary** [comment]
Adding absolute difference in bin C (Thong - Kevin) because the percentage plot doesn't take into account when binC in Kevin = 0, which happens frequently enough in bin C.
![BinCDiff](https://user-images.githubusercontent.com/10479549/75411455-237e1d00-58d4-11ea-9497-3f5a3c96639e.png)

Seems like there are ~10 points where I get 10 events less than Kevin.

FYI @cms-lpc-llp/delayedphoton

**Comment by thongonary** [comment]
I printed them out because I get paranoid. They come from the same binning strategy where I get 46 events and Kevin gets 56. Should be OK.

```
=====================================
Lambda = 100TeV. ctau = 1cm
Cat 2-photon |         46 |         56 |     -17.86%
=====================================
Lambda = 150TeV. ctau = 1cm
Cat 2-photon |         46 |         56 |     -17.86%
=====================================
Lambda = 200TeV. ctau = 1cm
Cat 2-photon |         46 |         56 |     -17.86%
=====================================
Lambda = 250TeV. ctau = 1cm
Cat 2-photon |         46 |         56 |     -17.86%
=====================================
Lambda = 300TeV. ctau = 1cm
Cat 2-photon |         46 |         56 |     -17.86%
=====================================
Lambda = 100TeV. ctau = 10cm
Cat 2-photon |         46 |         56 |     -17.86%
=====================================
Lambda = 150TeV. ctau = 10cm
Cat 2-photon |         46 |         56 |     -17.86%
=====================================
Lambda = 200TeV. ctau = 10cm
Cat 2-photon |         46 |         56 |     -17.86%
=====================================
Lambda = 250TeV. ctau = 10cm
Cat 2-photon |         46 |         56 |     -17.86%
=====================================
Lambda = 300TeV. ctau = 10cm
Cat 2-photon |         46 |         56 |     -17.86%
```
